"""Custom exceptions for RLM-RAG.

This module defines a hierarchy of exceptions for better error handling
and debugging across the RLM-RAG system.

Exception Hierarchy:
    RLMError (base)
    ├── ConfigurationError - Invalid configuration values
    ├── PreparationError - Document preparation failures
    ├── QueryError - Query execution failures
    │   ├── BudgetExhaustedError - Resource limits exceeded
    │   └── ExecutionError - REPL code execution failed
    └── LLMError - LLM-related failures
        └── CircuitOpenError - Circuit breaker is open

Example:
    >>> from rag_evaluator.rag_implementations.rlm_rag.exceptions import BudgetExhaustedError
    >>> try:
    ...     result = rag.query("complex question")
    ... except BudgetExhaustedError as e:
    ...     print(f"Query exceeded limits: {e}")
"""

from __future__ import annotations

from typing import Any


class RLMError(Exception):
    """Base exception for all RLM-RAG errors.

    All custom exceptions in RLM-RAG inherit from this class,
    enabling broad exception handling when needed.

    Example:
        >>> try:
        ...     rag.query("question")
        ... except RLMError as e:
        ...     logger.error(f"RLM-RAG error: {e}")
    """

    def __init__(self, message: str, details: dict[str, Any] | None = None):
        """Initialize with message and optional details.

        Args:
            message: Human-readable error description
            details: Optional dict with debugging information
        """
        super().__init__(message)
        self.message = message
        self.details = details or {}

    def __str__(self) -> str:
        if self.details:
            detail_str = ", ".join(f"{k}={v}" for k, v in self.details.items())
            return f"{self.message} ({detail_str})"
        return self.message


# ============================================================================
# Configuration Errors
# ============================================================================


class ConfigurationError(RLMError):
    """Invalid configuration provided to RLMConfig.

    Raised when configuration validation fails in RLMConfig.__post_init__.

    Attributes:
        invalid_fields: List of field names with invalid values
    """

    def __init__(self, message: str, invalid_fields: list[str] | None = None):
        super().__init__(message, details={"invalid_fields": invalid_fields or []})
        self.invalid_fields = invalid_fields or []


# ============================================================================
# Preparation Errors
# ============================================================================


class PreparationError(RLMError):
    """Document preparation failed.

    Raised when DocumentProcessor encounters errors during indexing.

    Attributes:
        documents_path: Path that was being processed
        failed_documents: List of documents that failed to process
    """

    def __init__(
        self,
        message: str,
        documents_path: str | None = None,
        failed_documents: list[str] | None = None,
    ):
        super().__init__(
            message,
            details={
                "documents_path": documents_path,
                "failed_documents": failed_documents or [],
            },
        )
        self.documents_path = documents_path
        self.failed_documents = failed_documents or []


# ============================================================================
# Query Errors
# ============================================================================


class QueryError(RLMError):
    """Query execution failed.

    Base class for errors that occur during query processing.
    """

    pass


class BudgetExhaustedError(QueryError):
    """Resource budget exhausted during exploration.

    Raised when the agent exceeds configured limits (REPL steps,
    file reads, sub-LLM calls, or tokens).

    Attributes:
        resource_type: Which resource was exhausted
        limit: The configured limit
        used: How much was used
    """

    def __init__(
        self,
        message: str,
        resource_type: str,
        limit: int,
        used: int,
    ):
        super().__init__(
            message,
            details={"resource_type": resource_type, "limit": limit, "used": used},
        )
        self.resource_type = resource_type
        self.limit = limit
        self.used = used


class ExecutionError(QueryError):
    """REPL code execution failed.

    Raised when code generated by the agent fails to execute
    or produces an error.

    Attributes:
        code: The code that failed
        error_type: Exception type name
        step: Which exploration step failed
    """

    def __init__(
        self,
        message: str,
        code: str | None = None,
        error_type: str | None = None,
        step: int | None = None,
    ):
        super().__init__(
            message,
            details={"code": code, "error_type": error_type, "step": step},
        )
        self.code = code
        self.error_type = error_type
        self.step = step


# ============================================================================
# LLM Errors
# ============================================================================


class LLMError(RLMError):
    """LLM-related failure.

    Base class for errors from the LLM layer (API calls, circuit breaker, etc.).
    """

    pass


class CircuitOpenError(LLMError):
    """Circuit breaker is open, API calls rejected.

    Raised when the circuit breaker has opened due to repeated
    API failures, preventing further calls until recovery.

    Attributes:
        timeout_remaining: Seconds until circuit attempts recovery
    """

    def __init__(self, message: str, timeout_remaining: float | None = None):
        super().__init__(message, details={"timeout_remaining": timeout_remaining})
        self.timeout_remaining = timeout_remaining


# ============================================================================
# Convenience Exports
# ============================================================================

__all__ = [
    "RLMError",
    "ConfigurationError",
    "PreparationError",
    "QueryError",
    "BudgetExhaustedError",
    "ExecutionError",
    "LLMError",
    "CircuitOpenError",
]
