"""Pydantic schemas for API request/response validation."""

from app.schemas.base import (
    BaseResponseSchema,
    BaseResponseWithUpdateSchema,
    BaseSchema,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.comparison import (
    AggregateMetrics,
    ComparisonCreate,
    ComparisonDetail,
    ComparisonList,
    ComparisonResponse,
    ComparisonSummary,
    CostMetricsDelta,
    EvaluationComparisonResult,
    MetricDelta,
    PerformanceMetricsDelta,
    PerQuestionDelta,
    SummaryMetricsDelta,
)
from app.schemas.evaluation import (
    CostMetrics,
    EvaluationControl,
    EvaluationCreate,
    EvaluationList,
    EvaluationResponse,
    EvaluationResultList,
    EvaluationResultResponse,
    EvaluationResultWithTestCase,
    EvaluationSummary,
    EvaluationWithDetails,
    MetricScore,
    PerformanceMetrics,
    ProgressCompletedEvent,
    ProgressErrorEvent,
    ProgressEvent,
    ProgressPausedEvent,
    ProgressResumedEvent,
    ProgressStartedEvent,
    ProgressUpdateEvent,
    SetBaselineRequest,
    SummaryMetrics,
)
from app.schemas.knowledge_base import (
    DocumentResponse,
    DocumentUploadResponse,
    KnowledgeBaseCreate,
    KnowledgeBaseList,
    KnowledgeBaseResponse,
    KnowledgeBaseSummary,
    KnowledgeBaseUpdate,
    KnowledgeBaseVersionResponse,
    KnowledgeBaseWithDocuments,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectList,
    ProjectResponse,
    ProjectSummary,
    ProjectUpdate,
)
from app.schemas.rag_config import (
    LLMProviderInfo,
    RAGConfigCreate,
    RAGConfigList,
    RAGConfigResponse,
    RAGConfigSummary,
    RAGConfigUpdate,
    RAGTypeInfo,
    RAGTypeParameter,
)
from app.schemas.test_set import (
    TestCaseBulkCreate,
    TestCaseBulkReview,
    TestCaseCreate,
    TestCaseResponse,
    TestCaseUpdate,
    TestSetCreate,
    TestSetExport,
    TestSetImport,
    TestSetList,
    TestSetResponse,
    TestSetSummary,
    TestSetUpdate,
    TestSetWithCases,
)
from app.schemas.test_template import (
    TestTemplateCreate,
    TestTemplateList,
    TestTemplateResponse,
    TestTemplateSummary,
    TestTemplateUpdate,
)
from app.schemas.webhook import (
    EvaluationWebhookPayload,
    GenerationWebhookPayload,
    WebhookCreate,
    WebhookDelivery,
    WebhookList,
    WebhookPayload,
    WebhookResponse,
    WebhookResponseSafe,
    WebhookTestRequest,
    WebhookTestResponse,
    WebhookUpdate,
)

__all__ = [
    # Base
    "BaseSchema",
    "BaseResponseSchema",
    "BaseResponseWithUpdateSchema",
    "PaginationParams",
    "PaginatedResponse",
    "HealthResponse",
    "ErrorDetail",
    "ErrorResponse",
    # Comparison
    "ComparisonCreate",
    "ComparisonResponse",
    "ComparisonDetail",
    "ComparisonSummary",
    "ComparisonList",
    "AggregateMetrics",
    "EvaluationComparisonResult",
    "MetricDelta",
    "SummaryMetricsDelta",
    "CostMetricsDelta",
    "PerformanceMetricsDelta",
    "PerQuestionDelta",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectSummary",
    "ProjectList",
    # Knowledge Base
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseResponse",
    "KnowledgeBaseWithDocuments",
    "KnowledgeBaseSummary",
    "KnowledgeBaseList",
    "KnowledgeBaseVersionResponse",
    "DocumentResponse",
    "DocumentUploadResponse",
    # Test Set
    "TestSetCreate",
    "TestSetUpdate",
    "TestSetResponse",
    "TestSetWithCases",
    "TestSetSummary",
    "TestSetList",
    "TestSetImport",
    "TestSetExport",
    "TestCaseCreate",
    "TestCaseUpdate",
    "TestCaseResponse",
    "TestCaseBulkCreate",
    "TestCaseBulkReview",
    # Test Template
    "TestTemplateCreate",
    "TestTemplateUpdate",
    "TestTemplateResponse",
    "TestTemplateSummary",
    "TestTemplateList",
    # RAG Config
    "RAGConfigCreate",
    "RAGConfigUpdate",
    "RAGConfigResponse",
    "RAGConfigSummary",
    "RAGConfigList",
    "RAGTypeInfo",
    "RAGTypeParameter",
    "LLMProviderInfo",
    # Evaluation
    "EvaluationCreate",
    "EvaluationResponse",
    "EvaluationWithDetails",
    "EvaluationSummary",
    "EvaluationList",
    "EvaluationResultResponse",
    "EvaluationResultWithTestCase",
    "EvaluationResultList",
    "EvaluationControl",
    "SetBaselineRequest",
    "MetricScore",
    "SummaryMetrics",
    "CostMetrics",
    "PerformanceMetrics",
    # Progress Events
    "ProgressEvent",
    "ProgressStartedEvent",
    "ProgressUpdateEvent",
    "ProgressCompletedEvent",
    "ProgressErrorEvent",
    "ProgressPausedEvent",
    "ProgressResumedEvent",
    # Webhook
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    "WebhookResponseSafe",
    "WebhookList",
    "WebhookTestRequest",
    "WebhookTestResponse",
    "WebhookDelivery",
    "WebhookPayload",
    "EvaluationWebhookPayload",
    "GenerationWebhookPayload",
]
